from __future__ import annotations

import json
from dataclasses import dataclass
from datetime import datetime
from decimal import Decimal
from pathlib import Path
from typing import Iterable

from axiom_engine.market_price_cache import compact_market_row, market_rows, unpack_market_row
from axiom_engine.previous_close import DailyClose, DailyCloseProvider, PreviousCloseError


@dataclass(frozen=True, slots=True)
class JsonCachedPreviousCloseProvider:
    """Read previous closes generated by the scheduled GitHub Actions job.

    This provider never performs network I/O. It is therefore safe for the
    public Render request path.
    """

    path: Path

    def previous_close(self, symbol: str, *, as_of: datetime | None = None) -> DailyClose:
        normalized = symbol.strip().upper()
        if not normalized:
            raise ValueError("symbol cannot be empty")
        try:
            payload = json.loads(self.path.read_text(encoding="utf-8"))
        except FileNotFoundError as exc:
            raise PreviousCloseError(f"previous-close cache not found: {self.path}") from exc
        except json.JSONDecodeError as exc:
            raise PreviousCloseError("previous-close cache is invalid JSON") from exc

        row = unpack_market_row(market_rows(payload).get(normalized))
        if row.get("close") in (None, "") or not row.get("session_date"):
            raise PreviousCloseError(f"previous close not cached for symbol: {normalized}")

        try:
            close = DailyClose(
                symbol=normalized,
                session_date=datetime.strptime(str(row["session_date"]), "%Y-%m-%d").date(),
                close=Decimal(str(row["close"])),
                currency=str(row["currency"]) if row.get("currency") else None,
                exchange_timezone=(
                    str(row["exchange_timezone"])
                    if row.get("exchange_timezone")
                    else None
                ),
                provider=str(row.get("provider") or "yahoo_finance"),
            )
        except (KeyError, TypeError, ValueError) as exc:
            raise PreviousCloseError(f"cached previous close is invalid: {normalized}") from exc

        if as_of is not None and close.session_date > as_of.date():
            raise PreviousCloseError(
                f"cached previous close for {normalized} is newer than requested as_of"
            )
        return close


def write_close_cache(path: Path, closes: Iterable[DailyClose], *, generated_at: datetime) -> None:
    del generated_at
    existing: dict[str, object] = {}
    if path.exists():
        try:
            raw = json.loads(path.read_text(encoding="utf-8"))
            existing = dict(market_rows(raw))
        except json.JSONDecodeError:
            existing = {}

    for close in closes:
        existing[close.symbol] = compact_market_row(close.close, close.session_date)

    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(
        json.dumps(dict(sorted(existing.items())), ensure_ascii=False, separators=(",", ":")) + "\n",
        encoding="utf-8",
    )
