from __future__ import annotations

import json
from dataclasses import dataclass
from datetime import datetime
from decimal import Decimal
from pathlib import Path
from typing import Iterable

from axiom_engine.previous_close import DailyClose, DailyCloseProvider, PreviousCloseError


@dataclass(frozen=True, slots=True)
class JsonCachedPreviousCloseProvider:
    """Read previous closes generated by the scheduled GitHub Actions job.

    This provider never performs network I/O. It is therefore safe for the
    public Render request path.
    """

    path: Path

    def previous_close(self, symbol: str, *, as_of: datetime | None = None) -> DailyClose:
        normalized = symbol.strip().upper()
        if not normalized:
            raise ValueError("symbol cannot be empty")
        try:
            payload = json.loads(self.path.read_text(encoding="utf-8"))
        except FileNotFoundError as exc:
            raise PreviousCloseError(f"previous-close cache not found: {self.path}") from exc
        except json.JSONDecodeError as exc:
            raise PreviousCloseError("previous-close cache is invalid JSON") from exc

        rows = payload.get("symbols") if isinstance(payload, dict) else None
        item = rows.get(normalized) if isinstance(rows, dict) else None
        if not isinstance(item, dict):
            raise PreviousCloseError(f"previous close not cached for symbol: {normalized}")

        try:
            close = DailyClose(
                symbol=normalized,
                session_date=datetime.strptime(str(item["session_date"]), "%Y-%m-%d").date(),
                close=Decimal(str(item["close"])),
                currency=str(item["currency"]) if item.get("currency") else None,
                exchange_timezone=(
                    str(item["exchange_timezone"])
                    if item.get("exchange_timezone")
                    else None
                ),
                provider=str(item.get("provider") or "github_actions_close_cache"),
            )
        except (KeyError, TypeError, ValueError) as exc:
            raise PreviousCloseError(f"cached previous close is invalid: {normalized}") from exc

        if as_of is not None and close.session_date > as_of.date():
            raise PreviousCloseError(
                f"cached previous close for {normalized} is newer than requested as_of"
            )
        return close


def write_close_cache(path: Path, closes: Iterable[DailyClose], *, generated_at: datetime) -> None:
    existing: dict[str, object] = {}
    if path.exists():
        try:
            raw = json.loads(path.read_text(encoding="utf-8"))
            if isinstance(raw, dict) and isinstance(raw.get("symbols"), dict):
                existing = dict(raw["symbols"])
        except json.JSONDecodeError:
            existing = {}

    for close in closes:
        existing[close.symbol] = close.to_dict()

    payload = {
        "schema_version": "1.0",
        "generated_at": generated_at.isoformat(),
        "symbols": dict(sorted(existing.items())),
    }
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
